

name: C CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C environment
      run: sudo apt-get install build-essential

    - name: Compile code
      run: gcc -o binary_tree src/binary_tree.c

    - name: Run tests
      run: ./binary_tree
